### ISSUE TITLE
Separator in the spreadsheet header

### ISSUE THREAD

**Issue by EmidioStani** [sparna-git/skos-play#77]
Hello Thomas,

I would like to use the [separator](https://skos-play.sparna.fr/play/convert#split) also on the header with the intention to have multiple URI described in it, is it possible ? I tried but it parses as 1 unique string.

Thanks,
Emidio

**Comment by tfrancart** [comment]
Hello !
You are right, I think the separator option is not supported here. The rationale is that if you want to assert more than one value for a predicate in the header, you can simply add more lines in the header, with the same predicate :

![image](https://user-images.githubusercontent.com/2728945/215317851-c7d5cb25-1470-427c-8f56-236e13571ce5.png)

I will see however if/how the separator option can be supported here. Let's keep this issue open.

**Comment by tfrancart** [comment]
This is now fixed

**Comment by EmidioStani** [comment]
Hello Thomas, thanks for taking care of this, but when I try on the SKOS Play ! I still see the concatenated string
